[Definition]
failregex = ^\{.*?"client_ip":"<HOST>".*?"uri":".*?(\.env|\.git|wp-admin|wp-login|phpmyadmin|\.aws|\.docker|actuator).*?".*?"status":404.*?\}$
            ^\{.*?"remote_ip":"<HOST>".*?"uri":".*?(\.env|\.git|wp-admin|wp-login|phpmyadmin|\.aws|\.docker|actuator).*?".*?"status":404.*?\}$
ignoreregex = 127\.0\.0\.1|172\.18\.|172\.20\.
