[caddy-auth]
enabled = true
port = http,https
filter = caddy-auth
logpath = /var/log/caddy/severinno-access.log
maxretry = 8
findtime = 600
bantime = 3600

[caddy-badbots]
enabled = true
port = http,https
filter = caddy-badbots
logpath = /var/log/caddy/severinno-access.log
maxretry = 3
findtime = 600
bantime = 86400
