#!/bin/bash
# ---------------------------------------------------------------------------
# setup-cloudflare-tunnel-ci.sh
# Configura Named Tunnel do Cloudflare (sem interação)
#
# Pré-requisitos:
#   1. ~/cloudflared (binário instalado)
#   2. ~/.cloudflared/cert.pem (autenticado via 'cloudflared tunnel login')
#
# Usage:
#   bash scripts/setup-cloudflare-tunnel-ci.sh [args]
#
# Exit codes:
#   0 — success
#   1 — failure
# ---------------------------------------------------------------------------

set -euo pipefail

CF="$HOME/cloudflared"
TUNNEL_NAME="severinno"
DOMAIN="severinno.com"
CONFIG_DIR="$HOME/.cloudflared"
CONFIG_FILE="$CONFIG_DIR/config.yml"

echo "🔧 Cloudflare Named Tunnel Setup"
echo ""

# Check auth
if [ ! -f "$CONFIG_DIR/cert.pem" ]; then
  echo "❌ Não autenticado. Execute: cloudflared tunnel login"
  exit 1
fi
echo "✅ Autenticado"

# Create tunnel (idempotent)
echo "🔧 Criando tunnel '$TUNNEL_NAME'..."
$CF tunnel create "$TUNNEL_NAME" 2>/dev/null || true
TUNNEL_ID=$($CF tunnel list | grep "$TUNNEL_NAME" | awk '{print $1}' | head -1)

if [ -z "$TUNNEL_ID" ]; then
  echo "❌ Tunnel não encontrado. Tunnels disponíveis:"
  $CF tunnel list
  exit 1
fi
echo "✅ Tunnel ID: $TUNNEL_ID"

# Route DNS
echo "🔧 Configurando DNS routing..."
$CF tunnel route dns "$TUNNEL_ID" "$DOMAIN" 2>/dev/null || true
$CF tunnel route dns "$TUNNEL_ID" "www.$DOMAIN" 2>/dev/null || true
echo "✅ DNS: $DOMAIN → tunnel"

# Create config
echo "🔧 Gerando config.yml..."
mkdir -p "$CONFIG_DIR"
cat > "$CONFIG_FILE" << EOF
# Severinno — Cloudflare Named Tunnel Configuration
# Auto-generated by setup-cloudflare-tunnel-ci.sh

tunnel: $TUNNEL_ID
credentials-file: $CONFIG_DIR/$TUNNEL_ID.json

ingress:
  - hostname: $DOMAIN
    service: http://localhost:3000
    originRequest:
      noTLSVerify: false
      connectTimeout: 30s
      keepAliveTimeout: 90s
  - hostname: www.$DOMAIN
    service: http://localhost:3000
  - service: http_status:404
EOF
echo "✅ Config: $CONFIG_FILE"

# Update systemd service
echo "🔧 Atualizando service..."
cat > /tmp/severinno-tunnel.service << EOF
[Unit]
Description=Severinno — Cloudflare Named Tunnel
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$USER
ExecStart=$CF tunnel --config $CONFIG_FILE run
Restart=always
RestartSec=5s
LimitNOFILE=65536
Environment=HOME=$HOME

[Install]
WantedBy=multi-user.target
EOF

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║         Setup Completo! 🎉                  ║"
echo "╠══════════════════════════════════════════════╣"
echo "║  Tunnel ID:  $TUNNEL_ID"
echo "║  Domínio:    https://$DOMAIN"
echo "║  Origin:     http://localhost:3000"
echo "║  Config:     $CONFIG_FILE"
echo "╠══════════════════════════════════════════════╣"
echo "║  Pra ativar:"
echo "║    sudo cp /tmp/severinno-tunnel.service \\"
echo "║      /etc/systemd/system/"
echo "║    sudo systemctl daemon-reload"
echo "║    sudo systemctl restart severinno-tunnel"
echo "╚══════════════════════════════════════════════╝"
