#!/usr/bin/env bash
# =============================================================================
# Setup Named Cloudflare Tunnel — severinno.com
# =============================================================================
# Prerequisites:
#   1. Create free Cloudflare account at https://dash.cloudflare.com/sign-up
#   2. Add severinno.com site (Free plan)
#   3. Update nameservers at Registro.br to CF nameservers
#   4. Run: cloudflared tunnel login (opens browser for auth)
#
# Usage:
#   chmod +x scripts/setup-named-tunnel.sh
#   ./scripts/setup-named-tunnel.sh
# =============================================================================

set -euo pipefail

TUNNEL_NAME="severinno"
DOMAIN="severinno.com"
CADDY_PORT=8443

echo "🌐 Setting up Named Cloudflare Tunnel for ${DOMAIN}"
echo ""

# ── Step 1: Check prerequisites ──────────────────────────────────────────────

echo "📋 Checking prerequisites..."

if ! command -v cloudflared &>/dev/null; then
    echo "❌ cloudflared not found. Install:"
    echo "   curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg"
    echo "   echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared $(lsb_release -cs) main' | sudo tee /etc/apt/sources.list.d/cloudflared.list"
    echo "   sudo apt update && sudo apt install -y cloudflared"
    exit 1
fi

if [ ! -f ~/.cloudflared/cert.pem ]; then
    echo "❌ No cert.pem found. Run first:"
    echo "   cloudflared tunnel login"
    echo "   (Opens browser to authenticate with Cloudflare)"
    exit 1
fi

echo "✅ cert.pem found"
echo "✅ cloudflared $(cloudflared --version 2>&1 | head -1)"

# ── Step 2: Create tunnel ────────────────────────────────────────────────────

echo ""
echo "🔧 Creating tunnel '${TUNNEL_NAME}'..."

if cloudflared tunnel list | grep -q "${TUNNEL_NAME}"; then
    echo "⚠️  Tunnel '${TUNNEL_NAME}' already exists, skipping creation"
    TUNNEL_ID=$(cloudflared tunnel list | grep "${TUNNEL_NAME}" | awk '{print $1}')
else
    cloudflared tunnel create "${TUNNEL_NAME}"
    TUNNEL_ID=$(cloudflared tunnel list | grep "${TUNNEL_NAME}" | awk '{print $1}')
fi

echo "✅ Tunnel ID: ${TUNNEL_ID}"

# ── Step 3: Create DNS record ────────────────────────────────────────────────

echo ""
echo "🌐 Configuring DNS for ${DOMAIN}..."

cloudflared tunnel route dns "${TUNNEL_NAME}" "${DOMAIN}" 2>/dev/null || echo "⚠️  DNS record may already exist"

echo "✅ DNS configured: ${DOMAIN} → tunnel"

# ── Step 4: Create tunnel config ─────────────────────────────────────────────

echo ""
echo "📝 Creating tunnel config..."

mkdir -p ~/.cloudflared

cat > ~/.cloudflared/config.yml <<EOF
# Cloudflare Named Tunnel Config — Severinno
# Generated by scripts/setup-named-tunnel.sh

tunnel: ${TUNNEL_ID}
credentials-file: /home/severinno/.cloudflared/${TUNNEL_ID}.json

ingress:
  # Main app
  - hostname: ${DOMAIN}
    service: http://localhost:3000
    originRequest:
      noTLSVerify: false
      connectTimeout: 30s
      tcpKeepAlive: 30s

  # API health check
  - hostname: api.${DOMAIN}
    service: http://localhost:3000

  # GlitchTip (error tracking)
  - hostname: errors.${DOMAIN}
    service: http://localhost:8000

  # Grafana (monitoring)
  - hostname: monitoring.${DOMAIN}
    service: http://localhost:3001

  # Catch-all
  - service: http_status:404
EOF

echo "✅ Config written to ~/.cloudflared/config.yml"

# ── Step 5: Create systemd service ───────────────────────────────────────────

echo ""
echo "🔧 Creating systemd service..."

sudo tee /etc/systemd/system/cloudflared.service > /dev/null <<EOF
[Unit]
Description=Cloudflare Named Tunnel for severinno.com
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/bin/cloudflared tunnel --config /home/severinno/.cloudflared/config.yml run
Restart=always
RestartSec=5
User=severinno
Environment=HOME=/home/severinno

# Hardening
NoNewPrivileges=true
ProtectSystem=strict
ReadWritePaths=/home/severinno/.cloudflared

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable cloudflared
sudo systemctl start cloudflared

echo "✅ cloudflared service installed and started"

# ── Step 6: Verify ──────────────────────────────────────────────────────────

echo ""
echo "🔍 Verifying tunnel..."

sleep 3

if sudo systemctl is-active --quiet cloudflared; then
    echo "✅ cloudflared service is running"
else
    echo "❌ cloudflared service failed to start"
    sudo systemctl status cloudflared --no-pager
    exit 1
fi

echo ""
echo "🎉 Setup complete!"
echo ""
echo "┌─────────────────────────────────────────────────────────────┐"
echo "│  🌐 https://severinno.com    → App principal               │"
echo "│  📊 https://monitoring.severinno.com → Grafana             │"
echo "│  🐛 https://errors.severinno.com → GlitchTip               │"
echo "│                                                             │"
echo "│  ⚠️  DNS propagation may take up to 24 hours               │"
echo "│  🔍 Test: curl -I https://severinno.com                     │"
echo "└─────────────────────────────────────────────────────────────┘"
echo ""
echo "Manage:"
echo "  sudo systemctl status cloudflared"
echo "  sudo systemctl restart cloudflared"
echo "  sudo journalctl -u cloudflared -f"
